// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: clibuilder/usecase4/proto/proto.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message containing the arguments.
type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Args          []string               `protobuf:"bytes,1,rep,name=args,proto3" json:"args,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_clibuilder_usecase4_proto_proto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_clibuilder_usecase4_proto_proto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_clibuilder_usecase4_proto_proto_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// The response message containing the output.
type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_clibuilder_usecase4_proto_proto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_clibuilder_usecase4_proto_proto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_clibuilder_usecase4_proto_proto_proto_rawDescGZIP(), []int{1}
}

func (x *RunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_clibuilder_usecase4_proto_proto_proto protoreflect.FileDescriptor

const file_clibuilder_usecase4_proto_proto_proto_rawDesc = "" +
	"\n" +
	"%clibuilder/usecase4/proto/proto.proto\x12\x06plugin\" \n" +
	"\n" +
	"RunRequest\x12\x12\n" +
	"\x04args\x18\x01 \x03(\tR\x04args\"'\n" +
	"\vRunResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage28\n" +
	"\x06Plugin\x12.\n" +
	"\x03Run\x12\x12.plugin.RunRequest\x1a\x13.plugin.RunResponseB\x1bZ\x19clibuilder/usecase4/protob\x06proto3"

var (
	file_clibuilder_usecase4_proto_proto_proto_rawDescOnce sync.Once
	file_clibuilder_usecase4_proto_proto_proto_rawDescData []byte
)

func file_clibuilder_usecase4_proto_proto_proto_rawDescGZIP() []byte {
	file_clibuilder_usecase4_proto_proto_proto_rawDescOnce.Do(func() {
		file_clibuilder_usecase4_proto_proto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_clibuilder_usecase4_proto_proto_proto_rawDesc), len(file_clibuilder_usecase4_proto_proto_proto_rawDesc)))
	})
	return file_clibuilder_usecase4_proto_proto_proto_rawDescData
}

var file_clibuilder_usecase4_proto_proto_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_clibuilder_usecase4_proto_proto_proto_goTypes = []any{
	(*RunRequest)(nil),  // 0: plugin.RunRequest
	(*RunResponse)(nil), // 1: plugin.RunResponse
}
var file_clibuilder_usecase4_proto_proto_proto_depIdxs = []int32{
	0, // 0: plugin.Plugin.Run:input_type -> plugin.RunRequest
	1, // 1: plugin.Plugin.Run:output_type -> plugin.RunResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_clibuilder_usecase4_proto_proto_proto_init() }
func file_clibuilder_usecase4_proto_proto_proto_init() {
	if File_clibuilder_usecase4_proto_proto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_clibuilder_usecase4_proto_proto_proto_rawDesc), len(file_clibuilder_usecase4_proto_proto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_clibuilder_usecase4_proto_proto_proto_goTypes,
		DependencyIndexes: file_clibuilder_usecase4_proto_proto_proto_depIdxs,
		MessageInfos:      file_clibuilder_usecase4_proto_proto_proto_msgTypes,
	}.Build()
	File_clibuilder_usecase4_proto_proto_proto = out.File
	file_clibuilder_usecase4_proto_proto_proto_goTypes = nil
	file_clibuilder_usecase4_proto_proto_proto_depIdxs = nil
}
